# Generated by Django 5.2.7 on 2025-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_plans', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='insurance_plans',
            field=models.ManyToManyField(blank=True, related_name='providers', to='insurance_plans.insuranceplan'),
        ),
    ]
