# Generated by Django 5.2.7 on 2025-10-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_networks', '0002_insurancenetwork_brand_insurancenetwork_service_area_and_more'),
        ('insurance_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insuranceplan',
            unique_together={('network', 'name')},
        ),
    ]
