# Generated by Django 5.2.7 on 2025-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_insurance_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='medmatch_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
