# Generated by Django 5.2.7 on 2025-10-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('plan_type', models.CharField(blank=True, choices=[('HMO', 'HMO'), ('PPO', 'PPO'), ('EPO', 'EPO'), ('POS', 'POS'), ('OTHER', 'Other')], max_length=20)),
                ('plan_code', models.CharField(blank=True, help_text='Optional internal or government code.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance_networks.insurancenetwork')),
            ],
        ),
    ]
