# Generated by Django 5.2.7 on 2025-10-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancenetwork',
            name='brand',
            field=models.CharField(blank=True, help_text="Top-level brand, e.g., 'Blue Cross Blue Shield', 'Aetna', 'UnitedHealthcare'.", max_length=80),
        ),
        migrations.AddField(
            model_name='insurancenetwork',
            name='service_area',
            field=models.CharField(blank=True, help_text="Comma-separated regions/states, e.g., 'TX' or 'MD,DC,VA'.", max_length=200),
        ),
        migrations.CreateModel(
            name='InsuranceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150, unique=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='insurance_networks.insurancenetwork')),
            ],
        ),
    ]
