# Generated by Django 5.2.7 on 2025-10-26 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_data', models.JSONField()),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('CONTACTED', 'Contacted'), ('APPT_SET', 'Appt Set'), ('NOT_INTERESTED', 'Not Interested')], default='SAVED', max_length=20)),
                ('initial_reason', models.TextField(blank=True, help_text='Why this provider was saved (e.g., from LLM summary).')),
                ('match_score_snapshot', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='searches.usersearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WEBFORM', 'Web Form'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('outcome', models.CharField(blank=True, help_text='e.g., Left VM, Spoke to front desk, Emailed', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='outreach.prospect')),
            ],
        ),
    ]
