# Generated by Django 5.2.7 on 2025-10-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospect',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
