# Generated by Django 5.2.7 on 2025-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='member_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
