# Generated by Django 5.2.7 on 2025-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_usersettings_group_id_usersettings_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='member_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='member_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
