# Generated by Django 5.2.7 on 2025-10-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_networks', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text="User's freeform description of their ailment or concern.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nemotron_response', models.JSONField(blank=True, null=True)),
                ('tavily_results', models.JSONField(blank=True, null=True)),
                ('insurance_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_networks.insurancenetwork')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, help_text='Explanation or reasoning provided by Nemotron or Tavily.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='searches.usersearch')),
            ],
        ),
    ]
